/*@ fixed */

#if defined(_MSC_VER)
  #pragma warning (disable:4018) // 'expression' : signed/unsigned mismatch
  #pragma warning (disable:4065) // switch statement contains 'default' but no 'case' labels
  #pragma warning (disable:4146) // unary minus operator applied to unsigned type, result still unsigned
  #pragma warning (disable:4244) // 'conversion' conversion from 'type1' to 'type2', possible loss of data
  #pragma warning (disable:4251) // 'identifier' : class 'type' needs to have dll-interface to be used by clients of class 'type2'
  #pragma warning (disable:4267) // 'var' : conversion from 'size_t' to 'type', possible loss of data
  #pragma warning (disable:4305) // 'identifier' : truncation from 'type1' to 'type2'
  #pragma warning (disable:4307) // 'operator' : integral constant overflow
  #pragma warning (disable:4309) // 'conversion' : truncation of constant value
  #pragma warning (disable:4334) // 'operator' : result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
  #pragma warning (disable:4355) // 'this' : used in base member initializer list
  #pragma warning (disable:4506) // no definition for inline function 'function'
  #pragma warning (disable:4800) // 'type' : forcing value to bool 'true' or 'false' (performance warning)
  #pragma warning (disable:4996) // The compiler encountered a deprecated declaration.
  #pragma warning (disable:4125) // decimal digit terminates octal escape sequence
#endif
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExampleSubProto.proto

#include "ExampleSubProto.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace ProtobufBlueprintSp {
constexpr ExampleSubProto::ExampleSubProto(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : int64_vals_()
  , _int64_vals_cached_byte_size_(0)
  , double_vals_()
  , string_vals_()
  , string_val_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , bytes_val_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , int32_val_(0){}
struct ExampleSubProtoDefaultTypeInternal {
  constexpr ExampleSubProtoDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ExampleSubProtoDefaultTypeInternal() {}
  union {
    ExampleSubProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ExampleSubProtoDefaultTypeInternal _ExampleSubProto_default_instance_;
}  // namespace ProtobufBlueprintSp
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_ExampleSubProto_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_ExampleSubProto_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_ExampleSubProto_2eproto = nullptr;

const uint32_t TableStruct_ExampleSubProto_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ProtobufBlueprintSp::ExampleSubProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ProtobufBlueprintSp::ExampleSubProto, int32_val_),
  PROTOBUF_FIELD_OFFSET(::ProtobufBlueprintSp::ExampleSubProto, string_val_),
  PROTOBUF_FIELD_OFFSET(::ProtobufBlueprintSp::ExampleSubProto, bytes_val_),
  PROTOBUF_FIELD_OFFSET(::ProtobufBlueprintSp::ExampleSubProto, int64_vals_),
  PROTOBUF_FIELD_OFFSET(::ProtobufBlueprintSp::ExampleSubProto, double_vals_),
  PROTOBUF_FIELD_OFFSET(::ProtobufBlueprintSp::ExampleSubProto, string_vals_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ProtobufBlueprintSp::ExampleSubProto)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::ProtobufBlueprintSp::_ExampleSubProto_default_instance_),
};

const char descriptor_table_protodef_ExampleSubProto_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025ExampleSubProto.proto\022\023ProtobufBluepri"
  "ntSp\"\211\001\n\017ExampleSubProto\022\021\n\tint32_val\030\001 "
  "\001(\005\022\022\n\nstring_val\030\002 \001(\t\022\021\n\tbytes_val\030\003 \001"
  "(\014\022\022\n\nint64_vals\030\004 \003(\003\022\023\n\013double_vals\030\005 "
  "\003(\001\022\023\n\013string_vals\030\006 \003(\tb\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_ExampleSubProto_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ExampleSubProto_2eproto = {
  false, false, 192, descriptor_table_protodef_ExampleSubProto_2eproto, "ExampleSubProto.proto", 
  &descriptor_table_ExampleSubProto_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_ExampleSubProto_2eproto::offsets,
  file_level_metadata_ExampleSubProto_2eproto, file_level_enum_descriptors_ExampleSubProto_2eproto, file_level_service_descriptors_ExampleSubProto_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_ExampleSubProto_2eproto_getter() {
  return &descriptor_table_ExampleSubProto_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_ExampleSubProto_2eproto(&descriptor_table_ExampleSubProto_2eproto);
namespace ProtobufBlueprintSp {

// ===================================================================

class ExampleSubProto::_Internal {
 public:
};

ExampleSubProto::ExampleSubProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  int64_vals_(arena),
  double_vals_(arena),
  string_vals_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:ProtobufBlueprintSp.ExampleSubProto)
}
ExampleSubProto::ExampleSubProto(const ExampleSubProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      int64_vals_(from.int64_vals_),
      double_vals_(from.double_vals_),
      string_vals_(from.string_vals_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  string_val_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    string_val_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_string_val().empty()) {
    string_val_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_string_val(), 
      GetArenaForAllocation());
  }
  bytes_val_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    bytes_val_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_bytes_val().empty()) {
    bytes_val_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_bytes_val(), 
      GetArenaForAllocation());
  }
  int32_val_ = from.int32_val_;
  // @@protoc_insertion_point(copy_constructor:ProtobufBlueprintSp.ExampleSubProto)
}

inline void ExampleSubProto::SharedCtor() {
string_val_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  string_val_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
bytes_val_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  bytes_val_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
int32_val_ = 0;
}

ExampleSubProto::~ExampleSubProto() {
  // @@protoc_insertion_point(destructor:ProtobufBlueprintSp.ExampleSubProto)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void ExampleSubProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  string_val_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  bytes_val_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ExampleSubProto::ArenaDtor(void* object) {
  ExampleSubProto* _this = reinterpret_cast< ExampleSubProto* >(object);
  (void)_this;
}
void ExampleSubProto::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ExampleSubProto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ExampleSubProto::Clear() {
// @@protoc_insertion_point(message_clear_start:ProtobufBlueprintSp.ExampleSubProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  int64_vals_.Clear();
  double_vals_.Clear();
  string_vals_.Clear();
  string_val_.ClearToEmpty();
  bytes_val_.ClearToEmpty();
  int32_val_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ExampleSubProto::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 int32_val = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          int32_val_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string string_val = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_string_val();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "ProtobufBlueprintSp.ExampleSubProto.string_val"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes bytes_val = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_bytes_val();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated int64 int64_vals = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt64Parser(_internal_mutable_int64_vals(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 32) {
          _internal_add_int64_vals(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated double double_vals = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_double_vals(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 41) {
          _internal_add_double_vals(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // repeated string string_vals = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_string_vals();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "ProtobufBlueprintSp.ExampleSubProto.string_vals"));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ExampleSubProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ProtobufBlueprintSp.ExampleSubProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 int32_val = 1;
  if (this->_internal_int32_val() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_int32_val(), target);
  }

  // string string_val = 2;
  if (!this->_internal_string_val().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_string_val().data(), static_cast<int>(this->_internal_string_val().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ProtobufBlueprintSp.ExampleSubProto.string_val");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_string_val(), target);
  }

  // bytes bytes_val = 3;
  if (!this->_internal_bytes_val().empty()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_bytes_val(), target);
  }

  // repeated int64 int64_vals = 4;
  {
    int byte_size = _int64_vals_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt64Packed(
          4, _internal_int64_vals(), byte_size, target);
    }
  }

  // repeated double double_vals = 5;
  if (this->_internal_double_vals_size() > 0) {
    target = stream->WriteFixedPacked(5, _internal_double_vals(), target);
  }

  // repeated string string_vals = 6;
  for (int i = 0, n = this->_internal_string_vals_size(); i < n; i++) {
    const auto& s = this->_internal_string_vals(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ProtobufBlueprintSp.ExampleSubProto.string_vals");
    target = stream->WriteString(6, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ProtobufBlueprintSp.ExampleSubProto)
  return target;
}

size_t ExampleSubProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ProtobufBlueprintSp.ExampleSubProto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int64 int64_vals = 4;
  {
    size_t data_size = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      Int64Size(this->int64_vals_);
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<int32_t>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _int64_vals_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated double double_vals = 5;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_double_vals_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // repeated string string_vals = 6;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(string_vals_.size());
  for (int i = 0, n = string_vals_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      string_vals_.Get(i));
  }

  // string string_val = 2;
  if (!this->_internal_string_val().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_string_val());
  }

  // bytes bytes_val = 3;
  if (!this->_internal_bytes_val().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_bytes_val());
  }

  // int32 int32_val = 1;
  if (this->_internal_int32_val() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_int32_val());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ExampleSubProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ExampleSubProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ExampleSubProto::GetClassData() const { return &_class_data_; }

void ExampleSubProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<ExampleSubProto *>(to)->MergeFrom(
      static_cast<const ExampleSubProto &>(from));
}


void ExampleSubProto::MergeFrom(const ExampleSubProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ProtobufBlueprintSp.ExampleSubProto)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  int64_vals_.MergeFrom(from.int64_vals_);
  double_vals_.MergeFrom(from.double_vals_);
  string_vals_.MergeFrom(from.string_vals_);
  if (!from._internal_string_val().empty()) {
    _internal_set_string_val(from._internal_string_val());
  }
  if (!from._internal_bytes_val().empty()) {
    _internal_set_bytes_val(from._internal_bytes_val());
  }
  if (from._internal_int32_val() != 0) {
    _internal_set_int32_val(from._internal_int32_val());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ExampleSubProto::CopyFrom(const ExampleSubProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ProtobufBlueprintSp.ExampleSubProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExampleSubProto::IsInitialized() const {
  return true;
}

void ExampleSubProto::InternalSwap(ExampleSubProto* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  int64_vals_.InternalSwap(&other->int64_vals_);
  double_vals_.InternalSwap(&other->double_vals_);
  string_vals_.InternalSwap(&other->string_vals_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &string_val_, lhs_arena,
      &other->string_val_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &bytes_val_, lhs_arena,
      &other->bytes_val_, rhs_arena
  );
  swap(int32_val_, other->int32_val_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ExampleSubProto::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_ExampleSubProto_2eproto_getter, &descriptor_table_ExampleSubProto_2eproto_once,
      file_level_metadata_ExampleSubProto_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace ProtobufBlueprintSp
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ProtobufBlueprintSp::ExampleSubProto* Arena::CreateMaybeMessage< ::ProtobufBlueprintSp::ExampleSubProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ProtobufBlueprintSp::ExampleSubProto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
